# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b54c2c0d0a9c33473d9ba288eafb92666c858d4151b6d1e869ae7ec7c6cd4760bdf5a90a62ddca36ca716e70a833d96d4ceefe9fd65f461a953cc572617e4e

test:
  secret_key_base: 1dbd65a907949ca20f5191bda68e54b009639ad96802cffdf7b19eae1400f2607dcaba90ce9e6d5b6ea0d426ca35b54f04aea7e3def0bd410d3cec5f52699639

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
